'use client'

import Link from 'next/link'
import { use, useState } from 'react'
import { ArrowLeft, Heart, Minus, Plus, ShoppingBag } from 'lucide-react'
import { catalog, getProduct, money } from '@/lib/catalog'

export default function ProductPage({params}:{params:Promise<{slug:string}>}){
 const {slug}=use(params); const product=getProduct(slug); if(!product) return <main className="simple-page not-found-page"><p className="kicker">404 / SENO STUDIO</p><h1>That piece<br/><em>isn't here.</em></h1><Link href="/" className="dark-button">Return to shop</Link></main>
 const [size,setSize]=useState(''); const [quantity,setQuantity]=useState(1); const [added,setAdded]=useState(false); const [open,setOpen]=useState('Details')
 const related=catalog.filter(item=>item.category===product.category&&item.slug!==product.slug).slice(0,3)
 return <main className="product-route"><Link className="back-link" href="/"><ArrowLeft size={13}/> Back to shop</Link><div className="product-detail"><div className="detail-gallery"><div className="detail-image"><img src={product.image} alt={product.name}/><span>{product.soldOut?'Sold out':'Available now'}</span></div><div className="detail-thumbs"><button className="active"><img src={product.image} alt=""/></button><button><img src={product.image} alt=""/></button></div></div><div className="detail-copy"><p className="kicker">{product.category} / SENO STUDIO</p><h1>{product.name}</h1><p className="detail-price">{money(product.price)}</p><p className="detail-description">A considered everyday layer, made in limited quantities with a focus on movement, texture and long-term wear.</p><div className="detail-rule"/><div className="detail-label">Colour <strong>{product.color}</strong></div><div className="size-row"><div className="detail-label">Select size</div><div className="size-options">{product.sizes.map(item=><button key={item} className={size===item?'selected':''} onClick={()=>setSize(item)}>{item}</button>)}</div></div><div className="quantity-row"><div className="detail-label">Quantity</div><div className="quantity-control"><button onClick={()=>setQuantity(Math.max(1,quantity-1))}><Minus size={14}/></button><span>{quantity}</span><button onClick={()=>setQuantity(quantity+1)}><Plus size={14}/></button></div></div><button className="detail-add" disabled={product.soldOut||!size} onClick={()=>setAdded(true)}>{added?'Added to bag':product.soldOut?'Sold out':size?`Add to bag — ${money(product.price*quantity)}`:'Select a size'}</button><div className="detail-links"><button><Heart size={16}/> Add to wishlist</button><button><ShoppingBag size={16}/> Shipping & returns</button></div><div className="accordions">{['Details','Sizing','Shipping & returns'].map(label=><div className="accordion" key={label}><button onClick={()=>setOpen(open===label?'':label)}><span>{label}</span><span>{open===label?'−':'+'}</span></button>{open===label&&<p>{label==='Sizing'?'Designed for a relaxed, true-to-size fit. See the size guide for measurements.':label==='Shipping & returns'?'Ships across India in 2–4 working days. Returns accepted within 7 days.':'Thoughtfully made in limited quantities with durable, comfortable materials.'}</p>}</div>)}</div></div></div><section className="related-section"><p className="kicker">YOU MAY ALSO LIKE</p><div className="related-grid">{related.map(item=><Link href={`/products/${item.slug}`} key={item.slug}><img src={item.image} alt={item.name}/><span>{item.name}</span><small>{money(item.price)}</small></Link>)}</div></section><section className="detail-footer"><p className="kicker">THE SENO STANDARD</p><h2>Designed for the<br/><em>in-between.</em></h2><p>Every piece is made to live beyond a single season. Explore the full collection for considered layers, soft structure and useful objects.</p></section></main>
}
